There is an extra space in line 6
The extra space is causing issues in Netlify from compling this theme. Used the recommended install settings (submodule).

Build time error is:
Error: "/opt/build/repo/themes/hugo-clarity/layouts/partials/logo.html:6:1": parse failed: template: partials/logo.html:6: illegal number syntax: "-"

Signed-off-by: Ben Williams <desertblade@gmail.com>